# Neural Network Programs using TensorFlow Keras

This notebook demonstrates Multilayer Perceptron, Forward & Backward Propagation, and a simple Autoencoder using TensorFlow Keras.

## Multilayer Perceptron (MLP)

In [ ]:

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# XOR dataset
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

# Build model
model = Sequential([
    Dense(4, input_dim=2, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

# Compile model
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

# Train model
model.fit(X, y, epochs=5000, verbose=0)

# Evaluate and predict
predictions = model.predict(X)
print("Predictions:")
print(predictions.round())


## Forward and Backward Propagation (Simple)

In [ ]:

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Sample data
X = np.array([[0.5, 0.8]])
y = np.array([[1]])

# Build model
model = Sequential([
    Dense(1, input_dim=2, activation='sigmoid')
])

# Compile
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.1), loss='mse')

# Train model (backprop happens here)
model.fit(X, y, epochs=500, verbose=0)

# Predict (forward pass)
output = model.predict(X)
print(f'Predicted Output: {output[0][0]:.4f}')


## Simple Autoencoder

In [ ]:

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Identity input data
X = np.identity(3)

# Build Autoencoder model
autoencoder = Sequential([
    Dense(2, input_dim=3, activation='sigmoid'),  # Encoder
    Dense(3, activation='sigmoid')                # Decoder
])

# Compile model
autoencoder.compile(optimizer='adam', loss='mse')

# Train model
autoencoder.fit(X, X, epochs=5000, verbose=0)

# Predict reconstructed outputs
reconstructed = autoencoder.predict(X)
print("\nOriginal Input:")
print(X)
print("\nReconstructed Output:")
print(reconstructed.round(3))


In [2]:
import numpy as np

# -------------------------
# 1️⃣ Initialize data
# -------------------------

# Example input features (4 samples, 2 features)
X = np.array([[0.5, 1.2],
              [1.5, 2.3],
              [0.3, 0.7],
              [2.0, 3.5]])

# Corresponding target values (regression problem)
y = np.array([[1.5],
              [3.0],
              [1.0],
              [4.5]])

# -------------------------
# 2️⃣ Define network structure
# -------------------------

input_size = 2       # Number of input features
hidden_size = 3      # Number of neurons in hidden layer
output_size = 1      # Regression → single output value
learning_rate = 0.01

# -------------------------
# 3️⃣ Initialize weights and biases
# -------------------------

np.random.seed(0)  # For reproducibility

w1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

w2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))
print(w1)
print(w2)
print(b1)
print(b2)

# -------------------------
# 4️⃣ Define activation function
# -------------------------

def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)


# -------------------------
# 5️⃣ Training: Forward and Backward Propagation
# -------------------------

epochs = 5000

for epoch in range(epochs):
    
    # --- Forward Propagation ---
    Z1 = np.dot(X, w1) + b1
    A1 = relu(Z1)

    Z2 = np.dot(A1, w2) + b2
    y_pred = Z2   # No activation for regression output

    # --- Compute Loss (MSE) ---
    loss = np.mean((y_pred - y)**2)

    # --- Backward Propagation ---
    dLoss_dy_pred = 2 * (y_pred - y) / y.shape[0]

    dLoss_dW2 = np.dot(A1.T, dLoss_dy_pred)
    dLoss_db2 = np.sum(dLoss_dy_pred, axis=0, keepdims=True)

    dA1 = np.dot(dLoss_dy_pred, w2.T)
    dZ1 = dA1 * relu_derivative(Z1)

    dLoss_dW1 = np.dot(X.T, dZ1)
    dLoss_db1 = np.sum(dZ1, axis=0, keepdims=True)

    # --- Update Weights and Biases ---
    w2 -= learning_rate * dLoss_dW2
    b2 -= learning_rate * dLoss_db2

    w1 -= learning_rate * dLoss_dW1
    b1 -= learning_rate * dLoss_db1

    # Print loss every 500 epochs
    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# -------------------------
# 6️⃣ Final Prediction
# -------------------------

print("\nFinal Predictions:")
print(y_pred)


[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
[[ 0.95008842]
 [-0.15135721]
 [-0.10321885]]
[[0. 0. 0.]]
[[0.]]


In [5]:
import numpy as np

# -------------------------
# 1️⃣ Initialize data
# -------------------------

# Example input features (4 samples, 2 features)
X = np.array([[0.5, 1.2],
              [1.5, 2.3],
              [0.3, 0.7],
              [2.0, 3.5]])

# Corresponding target values (regression problem)
y = np.array([[1.5],
              [3.0],
              [1.0],
              [4.5]])

# -------------------------
# 2️⃣ Define network structure
# -------------------------

input_size = 2       # Number of input features
hidden_size = 3      # Number of neurons in hidden layer
output_size = 1      # Regression → single output value
learning_rate = 0.01

# -------------------------
# 3️⃣ Initialize weights and biases
# -------------------------

np.random.seed(0)  # For reproducibility

W1 = np.random.randn(input_size, hidden_size)
b1 = np.ones((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

print(X @ W1 + b1)
# -------------------------
# 4️⃣ Define activation function
# -------------------------

def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

[[ 4.57109801  3.44114819  0.31663554]
 [ 8.80013288  5.89561919  0.22036785]
 [ 3.09784094  2.42733776  0.60952688]
 [12.37123089  8.33676738 -0.46299661]]


In [18]:
import numpy as np

X = np.array([[0.5, 1.2],
              [1.5, 2.3],
              [0.3, 0.7],
              [2.0, 3.5]])
y = np.array([[1.5],
              [3.0],
              [1.0],
              [4.5]])

np.random.seed(0)
W1 = np.random.randn(2, 3)
b1 = np.zeros((1, 3))
W2 = np.random.randn(3, 1)
b2 = np.zeros((1, 1))

def relu(x): return np.maximum(0, x)
def drelu(x): return (x > 0).astype(float)

for i in range(5000+1):
    Z1 = X @ W1 + b1
    A1 = relu(Z1)
    y_pred = A1 @ W2 + b2
    y_pred = relu(y_pred)
    
    loss = np.mean((y_pred - y)**2)
    
    d = 2 * (y_pred - y) / len(y)
    W2 -= 0.01 * (A1.T @ d)
    b2 -= 0.01 * np.sum(d, axis=0, keepdims=True)
    
    dz = (d @ W2.T) * drelu(Z1)
    W1 -= 0.01 * (X.T @ dz)
    b1 -= 0.01 * np.sum(dz, axis=0, keepdims=True)
    if i % 500 == 0:
        print(f"loss at epoch {i} is {loss}")




loss at epoch 0 is 10.840384117036951
loss at epoch 500 is 0.006316052775982847
loss at epoch 1000 is 0.005633293165715777
loss at epoch 1500 is 0.0051110002426821375
loss at epoch 2000 is 0.004695519643113541
loss at epoch 2500 is 0.004358526750247413
loss at epoch 3000 is 0.004080618914922213
loss at epoch 3500 is 0.00384811966895786
loss at epoch 4000 is 0.0036511501691895527
loss at epoch 4500 is 0.0034824211186251434
loss at epoch 5000 is 0.003336452408107517


In [10]:
import numpy as np
x = np.array([
    [1.5,0.2],
    [1.7,2.3],
    [3.2,1.3],
    [5.2,0.1]
])

y = np.array([
    [1.7],
    [1.3],
    [1.8],
    [2.3]
])

def relu(x):
    return np.maximum(0,x)

def relu_derivative(x):
    return (x > 0).astype(float)

lr = 0.001

# Weight initialization (scaled down)
first_layer_weight = np.random.randn(2,3) * 0.1
first_layer_bias = np.ones((1,3))

second_layer_weights = np.random.randn(3,1) * 0.1
second_layer_bias = np.ones((1,1))

for i in range(4000+1):
    first_layer_ip = (x @ first_layer_weight) + first_layer_bias
    first_layer_op = relu(first_layer_ip)

    second_layer_ip = (first_layer_op @ second_layer_weights) + second_layer_bias

    loss = np.mean((y - second_layer_ip)**2)

    dw2 = 2 * (y - second_layer_ip) / len(y)
    second_layer_weights -= lr * (first_layer_op.T @ dw2)
    second_layer_bias -= lr * np.sum(dw2, axis=0, keepdims=True)

    dw1 = (dw2 @ second_layer_weights.T) * relu_derivative(first_layer_ip)
    first_layer_weight -= lr * (x.T @ dw1)
    first_layer_bias -= lr * np.sum(dw1, axis=0, keepdims=True)

    if i % 500 == 0:
        print(f"loss at epoch {i} is {loss}")



loss at epoch 0 is 0.4975787624380904
loss at epoch 500 is inf
loss at epoch 1000 is inf
loss at epoch 1500 is inf
loss at epoch 2000 is inf
loss at epoch 2500 is inf


C:\Users\athar\AppData\Local\Temp\ipykernel_41260\1910722032.py:37: RuntimeWarning: overflow encountered in square
  loss = np.mean((y - second_layer_ip)**2)
C:\Users\athar\AppData\Local\Temp\ipykernel_41260\1910722032.py:40: RuntimeWarning: overflow encountered in matmul
  second_layer_weights -= lr * (first_layer_op.T @ dw2)


loss at epoch 3000 is inf
loss at epoch 3500 is inf
loss at epoch 4000 is inf


In [12]:
import numpy as np

# Data (now as numpy array and normalized)
x = np.array([
    [1.5,0.2],
    [1.7,2.3],
    [3.2,1.3],
    [5.2,0.1]
])
x = x / 5.2

y = np.array([
    [1.7],
    [1.3],
    [1.8],
    [2.3]
])

# Activation: tanh
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

# Initialize weights (small values)
first_layer_weight = np.random.randn(2,3) * 0.1
first_layer_bias = np.zeros((1,3))

second_layer_weights = np.random.randn(3,1) * 0.1
second_layer_bias = np.zeros((1,1))

lr = 0.01

for i in range(4000+1):
    # Forward
    first_layer_ip = (x @ first_layer_weight) + first_layer_bias
    first_layer_op = tanh(first_layer_ip)

    second_layer_ip = (first_layer_op @ second_layer_weights) + second_layer_bias

    loss = np.mean((y - second_layer_ip)**2)

    # Backward
    dw2 = 2 * (y - second_layer_ip) / len(y)
    second_layer_weights -= lr * (first_layer_op.T @ dw2)
    second_layer_bias -= lr * np.sum(dw2, axis=0, keepdims=True)

    dw1 = (dw2 @ second_layer_weights.T) * tanh_derivative(first_layer_ip)
    first_layer_weight -= lr * (x.T @ dw1)
    first_layer_bias -= lr * np.sum(dw1, axis=0, keepdims=True)

    if i % 500 == 0:
        print(f"loss at epoch {i} is {loss}")


loss at epoch 0 is 3.27435206660821
loss at epoch 500 is 5.608409578651938e+31
loss at epoch 1000 is 1.4879735431412894e+65
loss at epoch 1500 is 3.947759581461618e+98
loss at epoch 2000 is 1.0473845979896038e+132
loss at epoch 2500 is 2.778828025033093e+165
loss at epoch 3000 is 7.372540332873904e+198
loss at epoch 3500 is 1.956017085987366e+232
loss at epoch 4000 is 5.189531244223238e+265
